[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Zheng1013 <love24175160@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
redis = "^5.0.1"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
